name: Test Security Standards

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2', '8.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml
        
    - name: Validate composer.json
      run: composer validate --strict
      
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Install PHPCS standards
      run: ./bin/install-security-standards
      
    - name: Test ruleset validity
      run: phpcs --standard=CommonSecurity -e
      
    - name: Test flexible ruleset
      run: phpcs --standard=CommonSecurity/Flexible -e
      
    - name: Run tests on sample dangerous code
      run: |
        echo '<?php eval($_GET["code"]); ?>' > test.php
        ! phpcs --standard=CommonSecurity test.php || exit 1
        rm test.php
        
    - name: Test project config generator
      run: |
        echo "none" | php bin/generate-project-config
        test -f phpcs-security-custom.xml
